### ISSUE TITLE
How can I find the paper "Generating positive bounding boxes for balanced training of object detectors"

### ISSUE THREAD

**Issue by xunhen** [kemaloksuz/ObjectDetectionImbalance#5]

**Comment by kemaloksuz** [comment]
The paper is under review now for WACV currently. Probably, we will upload it to arXiv once the results are released on September 16. I will let you know, then close this issue.

**Comment by xunhen** [comment]
> The paper is under review now for WACV currently. Probably, we will upload it to arXiv once the results are released on September 16. I will let you know, then close this issue.

Thank you

**Comment by 14zwyan** [comment]
Hi, is there any progress of thie paper?

**Comment by kemaloksuz** [comment]
Thanks for your interest. We have uploaded it today, arXiv will release it next Monday.

**Comment by 14zwyan** [comment]
> Thanks for your interest. We have uploaded it today, arXiv will release it next Monday.

Thank your!

**Comment by kemaloksuz** [comment]
You can find a link to the paper in the repo.
